name       : mergerfs
version    : 2.24.2
release    : 1
source     :
    - https://github.com/trapexit/mergerfs/releases/download/2.24.2/mergerfs-2.24.2.tar.gz : 91401b54e04ae240d5f8d3ae74946a88afd9ddb7056e212a0e25eac5682fa9ea
license    : ISC
component  : system.utils
summary    : A featureful union filesystem
description: |
    Mergerfs is a union filesystem geared towards simplifying storage and management of files across numerous commodity storage devices
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
