name       : mergerfs
version    : 2.25.1
release    : 2
source     :
    - https://github.com/trapexit/mergerfs/releases/download/2.25.1/mergerfs-2.25.1.tar.gz : f604ad04aad99983c5f91e50e27275deefab4797c1343d8e0cf3664d1ca53fc5
license    : ISC
component  : system.utils
summary    : A featureful union filesystem
description: |
    Mergerfs is a union filesystem geared towards simplifying storage and management of files across numerous commodity storage devices
build      : |
    %make
install    : |
    %make_install PREFIX=/usr
